### ISSUE TITLE
designer wanted logo

### ISSUE THREAD

**Issue by PiotrPerak** [jason-roberts/TempTest#4]
I'm looking for someone that could make logo for my NuGet package.
http://www.nuget.org/packages/NUnit.Snippets

**Comment by jason-roberts** [comment]
Hi, you need to add an issue like this to your own repo, not in this one.

**Comment by jason-roberts** [comment]
@PiotrPerak I created this for you: https://github.com/PiotrPerak/NUnit.Snippets/issues/1
